/**
 * Compact GitHub PR conversation for injection into EnrichedContext.
 *
 * Coordinator-fetched comments are redacted, truncated, and packed under a
 * hard byte cap. Packing order prefers teammate decisions over bot noise.
 * Finding/comment bodies stay (unlike priorRounds) because the wording is
 * the product; overflow is dropped, not paraphrased.
 */

export const GITHUB_CONVERSATION_MAX_BYTES = 16 * 1024
export const GITHUB_COMMENT_BODY_MAX_BYTES = 2 * 1024

/** Footer appended to posted Agamotto GitHub comments — used to tag source. */
export const AGAMOTTO_REVIEW_FOOTER =
  '*Generated by Agamotto (corr · sec · conv · perf · style)*'

export const EMPTY_GITHUB_CONVERSATION: GithubConversationPack = {
  items: [],
  omitted: false,
}

export enum GithubCommentKind {
  INLINE = 'INLINE',
  DISCUSSION = 'DISCUSSION',
  REVIEW_BODY = 'REVIEW_BODY',
}

export enum GithubCommentSource {
  HUMAN = 'HUMAN',
  AGAMOTTO = 'AGAMOTTO',
  BOT = 'BOT',
}

/** Bot type wins; otherwise the Agamotto footer; otherwise human. */
export function classifyGithubCommentSource(
  user: { type?: string | null } | null | undefined,
  body: string
): GithubCommentSource {
  if (user?.type === 'Bot') return GithubCommentSource.BOT
  if (body.includes(AGAMOTTO_REVIEW_FOOTER)) return GithubCommentSource.AGAMOTTO
  return GithubCommentSource.HUMAN
}

export interface RawGithubComment {
  kind: GithubCommentKind
  source: GithubCommentSource
  id: number
  author?: string
  createdAt: string
  body: string
  path?: string
  line?: number
}

export interface GithubConversationItem {
  kind: GithubCommentKind
  id: number
  author?: string
  createdAt: string
  body: string
  path?: string
  line?: number
}

export interface GithubConversationPack {
  items: GithubConversationItem[]
  omitted: boolean
}

const BODY_TRUNCATION_SENTINEL = '\n[comment truncated]'

function utf8Bytes(value: string): number {
  return Buffer.byteLength(value, 'utf8')
}

/** Strip credential-like substrings before any model prompt or log. */
export function redactCredentialLike(body: string): string {
  return body
    .replace(
      /-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g,
      '[redacted]'
    )
    .replace(/\bghp_[A-Za-z0-9_]{8,}/g, '[redacted]')
    .replace(/\bgho_[A-Za-z0-9_]{8,}/g, '[redacted]')
    .replace(/\bgithub_pat_[A-Za-z0-9_]{8,}/g, '[redacted]')
    .replace(/\bsk-[A-Za-z0-9_-]{16,}/g, '[redacted]')
    .replace(/\bBearer\s+\S+/gi, '[redacted]')
}

function truncateBody(body: string): string {
  if (utf8Bytes(body) <= GITHUB_COMMENT_BODY_MAX_BYTES) return body
  const budget =
    GITHUB_COMMENT_BODY_MAX_BYTES - utf8Bytes(BODY_TRUNCATION_SENTINEL)
  let end = Math.min(body.length, budget)
  while (end > 0 && utf8Bytes(body.slice(0, end)) > budget) {
    end -= 1
  }
  return body.slice(0, end) + BODY_TRUNCATION_SENTINEL
}

function tier(raw: RawGithubComment): number {
  if (raw.source === GithubCommentSource.BOT) return 3
  if (raw.source === GithubCommentSource.AGAMOTTO) return 2
  if (
    raw.kind === GithubCommentKind.REVIEW_BODY ||
    raw.kind === GithubCommentKind.DISCUSSION
  ) {
    return 0
  }
  return 1
}

function toItem(raw: RawGithubComment): GithubConversationItem {
  const item: GithubConversationItem = {
    kind: raw.kind,
    id: raw.id,
    createdAt: raw.createdAt,
    body: truncateBody(redactCredentialLike(raw.body)),
  }
  if (raw.author) item.author = raw.author
  if (raw.path) item.path = raw.path
  if (typeof raw.line === 'number') item.line = raw.line
  return item
}

function packBytes(items: GithubConversationItem[]): number {
  return utf8Bytes(JSON.stringify(items))
}

/** Map raw comments into a capped pack. Newer items first within each tier. */
export function formatGithubConversation(
  raw: RawGithubComment[]
): GithubConversationPack {
  const sorted = [...raw].sort((a, b) => {
    const tierDelta = tier(a) - tier(b)
    if (tierDelta !== 0) return tierDelta
    return b.createdAt.localeCompare(a.createdAt)
  })
  const items: GithubConversationItem[] = []
  for (const comment of sorted) {
    const next = [...items, toItem(comment)]
    if (packBytes(next) > GITHUB_CONVERSATION_MAX_BYTES) {
      return { items, omitted: true }
    }
    items.push(next[next.length - 1])
  }
  return { items, omitted: false }
}

export function githubConversationStats(pack: GithubConversationPack): {
  itemCount: number
  omitted: boolean
} {
  return { itemCount: pack.items.length, omitted: pack.omitted }
}

export function formatGithubConversationActivityLabel(
  itemCount: number,
  omitted: boolean
): string {
  if (itemCount === 0 && !omitted) return 'No GitHub conversation'
  const base = `Loaded ${itemCount} GitHub comment${itemCount === 1 ? '' : 's'}`
  return omitted ? `${base} (truncated)` : base
}

export function formatGithubConversationActivity(
  pack: GithubConversationPack
): string {
  return formatGithubConversationActivityLabel(pack.items.length, pack.omitted)
}

export function formatGithubConversationFetchFailed(): string {
  return 'GitHub conversation unavailable'
}
