-- Baseline schema for a fresh Agamotto install.
-- All app tables, functions, policies, and grants live in the agamotto schema.
-- The vector extension is cluster-level (not schema-scoped).
create extension if not exists vector;

create schema if not exists agamotto;

grant usage on schema agamotto to authenticated;

grant usage on schema agamotto to service_role;

grant usage on schema agamotto to anon;

-- ============================================================
-- memories
-- User-defined review criteria and team coding standards.
-- ============================================================
create table if not exists agamotto.memories (
  id uuid primary key default gen_random_uuid(),
  content text not null,
  tags text[] not null default '{}',
  context text not null default '', -- empty = global; set to repo name to scope
  created_at timestamptz not null default now()
);

create index if not exists memories_context_idx on agamotto.memories (context);

-- ============================================================
-- review_history
-- Full output of every submitted PR review.
-- ============================================================
create table if not exists agamotto.review_history (
  id uuid primary key default gen_random_uuid(),
  pr_url text not null,
  repo_name text not null,
  pr_title text not null,
  author text not null,
  reviewed_at timestamptz not null default now(),
  finding_count integer not null default 0,
  summary text not null default '',
  raw_json jsonb not null default '{}'
);

create index if not exists review_history_repo_idx on agamotto.review_history (repo_name);

create index if not exists review_history_author_idx on agamotto.review_history (author);

-- ============================================================
-- review_checkpoints
-- Pass/fail state for each review stage.
-- agent_name is nullable: single-agent stages leave it null;
-- parallel domain agents set it so they don't collide on DOMAIN.
-- ============================================================
create table if not exists agamotto.review_checkpoints (
  id uuid primary key default gen_random_uuid(),
  review_id text not null,
  stage text not null,
  agent_name text,
  passed boolean not null,
  message text,
  payload jsonb,
  recorded_at timestamptz not null default now(),
  unique nulls not distinct (review_id, stage, agent_name)
);

create index if not exists review_checkpoints_review_idx on agamotto.review_checkpoints (review_id);

-- ============================================================
-- reviews
-- Durable review state. Replaces the in-process review-cache.ts Map.
-- ============================================================
create table if not exists agamotto.reviews (
  id text primary key, -- UUID generated by the start route
  pr_url text not null,
  pr_metadata jsonb not null default '{}', -- { owner, repo, number, title, head, base, author }
  mode text not null default 'full', -- 'full' | 'quick'
  status text not null default 'RUNNING', -- RUNNING | COMPLETE | ERROR
  result jsonb, -- serialized PRReview (set when COMPLETE)
  submission jsonb, -- serialized ReviewSubmission (set on finalize)
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reviews_status_idx on agamotto.reviews (status);

create index if not exists reviews_created_at_idx on agamotto.reviews (created_at desc);

-- ============================================================
-- tracked_prs
-- The PR review queue: one row per open PR per configured repo.
-- ============================================================
create table if not exists agamotto.tracked_prs (
  id uuid primary key default gen_random_uuid(),
  owner text not null,
  repo text not null,
  pr_number int not null,
  pr_url text not null,
  pr_title text,
  pr_author text,
  pr_opened_at timestamptz,
  pr_closed_at timestamptz,
  -- OPEN: awaiting review
  -- IN_REVIEW: review currently running
  -- REVIEWED: review submitted; new commits flip back to OPEN
  -- CLOSED: PR merged or closed on GitHub
  status text not null default 'OPEN',
  updated_since_review boolean not null default false, -- true when synchronize event arrives after REVIEWED
  last_review_id text references agamotto.reviews (id) on delete set null,
  review_count int not null default 0,
  source text not null default 'MANUAL', -- MANUAL | WEBHOOK
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner, repo, pr_number)
);

create index if not exists tracked_prs_status_idx on agamotto.tracked_prs (status);

create index if not exists tracked_prs_repo_idx on agamotto.tracked_prs (owner, repo);

-- ============================================================
-- configured_repos
-- Repos the admin has registered for PR review tracking.
-- ============================================================
create table if not exists agamotto.configured_repos (
  id uuid primary key default gen_random_uuid(),
  owner text not null,
  name text not null,
  webhook_secret text, -- set when webhook is installed; null = no webhook
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner, name)
);

-- ============================================================
-- settings
-- Key/value store for in-app configuration.
-- ============================================================
create table if not exists agamotto.settings (
  key text primary key,
  value jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

-- ============================================================
-- Helper functions
-- ============================================================
create or replace function agamotto.set_updated_at () returns trigger
set
  search_path = agamotto as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace function agamotto.manage_tracked_pr_on_reviewed () returns trigger language plpgsql
set
  search_path = agamotto as $$
begin
  if new.status = 'REVIEWED' and old.status is distinct from 'REVIEWED' then
    new.review_count = old.review_count + 1;
    new.updated_since_review = false;
  end if;
  return new;
end;
$$;

-- ============================================================
-- Triggers
-- ============================================================
create trigger reviews_updated_at
before update on agamotto.reviews for each row
execute function agamotto.set_updated_at ();

create trigger tracked_prs_updated_at
before update on agamotto.tracked_prs for each row
execute function agamotto.set_updated_at ();

create trigger configured_repos_updated_at
before update on agamotto.configured_repos for each row
execute function agamotto.set_updated_at ();

create trigger settings_updated_at
before update on agamotto.settings for each row
execute function agamotto.set_updated_at ();

create trigger tracked_prs_on_reviewed
before update on agamotto.tracked_prs for each row
execute function agamotto.manage_tracked_pr_on_reviewed ();

-- ============================================================
-- Row-level security
-- ============================================================
alter table agamotto.memories enable row level security;

alter table agamotto.review_history enable row level security;

alter table agamotto.review_checkpoints enable row level security;

alter table agamotto.reviews enable row level security;

alter table agamotto.tracked_prs enable row level security;

alter table agamotto.configured_repos enable row level security;

alter table agamotto.settings enable row level security;

-- Authenticated reads
create policy "authenticated can read memories" on agamotto.memories for
select
  to authenticated using (true);

create policy "authenticated can read review_history" on agamotto.review_history for
select
  to authenticated using (true);

create policy "authenticated can read review_checkpoints" on agamotto.review_checkpoints for
select
  to authenticated using (true);

create policy "authenticated can read reviews" on agamotto.reviews for
select
  to authenticated using (true);

create policy "authenticated can read tracked_prs" on agamotto.tracked_prs for
select
  to authenticated using (true);

create policy "authenticated can read configured_repos" on agamotto.configured_repos for
select
  to authenticated using (true);

create policy "authenticated can read settings" on agamotto.settings for
select
  to authenticated using (true);

-- Authenticated users can manage configured_repos and settings (admin actions)
create policy "authenticated can insert configured_repos" on agamotto.configured_repos for insert to authenticated
with
  check (true);

create policy "authenticated can update configured_repos" on agamotto.configured_repos
for update
  to authenticated using (true);

create policy "authenticated can delete configured_repos" on agamotto.configured_repos for delete to authenticated using (true);

create policy "authenticated can upsert settings" on agamotto.settings for insert to authenticated
with
  check (true);

create policy "authenticated can update settings" on agamotto.settings
for update
  to authenticated using (true);

-- Explicit ALL policies for service_role (belt-and-suspenders if BYPASSRLS is unset locally)
create policy "service_role can manage reviews" on agamotto.reviews for all to service_role using (true)
with
  check (true);

create policy "service_role can manage tracked_prs" on agamotto.tracked_prs for all to service_role using (true)
with
  check (true);

create policy "service_role can manage configured_repos" on agamotto.configured_repos for all to service_role using (true)
with
  check (true);

create policy "service_role can manage settings" on agamotto.settings for all to service_role using (true)
with
  check (true);

create policy "service_role can manage memories" on agamotto.memories for all to service_role using (true)
with
  check (true);

create policy "service_role can manage review_history" on agamotto.review_history for all to service_role using (true)
with
  check (true);

create policy "service_role can manage review_checkpoints" on agamotto.review_checkpoints for all to service_role using (true)
with
  check (true);

-- ============================================================
-- Table privileges
-- RLS is a second layer — roles still need base table grants.
-- ============================================================
grant all on agamotto.reviews to service_role;

grant
select
  on agamotto.reviews to authenticated;

grant all on agamotto.tracked_prs to service_role;

grant
select
  on agamotto.tracked_prs to authenticated;

grant all on agamotto.configured_repos to service_role;

grant all on agamotto.configured_repos to authenticated;

grant all on agamotto.settings to service_role;

grant all on agamotto.settings to authenticated;

grant all on agamotto.memories to service_role;

grant
select
  on agamotto.memories to authenticated;

grant all on agamotto.review_history to service_role;

grant
select
  on agamotto.review_history to authenticated;

grant all on agamotto.review_checkpoints to service_role;

grant
select
  on agamotto.review_checkpoints to authenticated;
